spring.application.name=todozao

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/todo_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



## 4. Como rodar localmente com `.env`

## Se estiver usando **IntelliJ**:
## - Vá em Run ? Edit Configurations
## - Na aba "Environment variables", cole:

DATABASE_URL=jdbc:postgresql://localhost:5432/todozao;DATABASE_USERNAME=postgres;DATABASE_PASSWORD=sua_senha